[2024-07-23 17:18:02,374: INFO: main: welcome to our custom log]
[2024-07-23 17:18:26,937: INFO: main: welcome to our custom log]
[2024-07-24 11:10:32,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:11:46,494: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:12:53,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:13:15,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:15:58,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:16:34,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:17:24,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:17:24,719: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 11:17:24,719: INFO: common: created directory at: artifacts]
[2024-07-24 11:17:24,724: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 11:17:24,726: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:18:01,576: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:39:30,709: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:39:30,724: ERROR: main: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 37, in read_yaml
    raise e
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2
[2024-07-24 11:40:18,984: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:40:18,984: ERROR: main: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2]
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 37, in read_yaml
    raise e
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2
[2024-07-24 11:42:25,788: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:42:25,788: ERROR: main: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2]
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 37, in read_yaml
    raise e
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2
[2024-07-24 11:43:18,769: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:43:18,787: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:43:18,788: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 11:43:18,788: INFO: common: created directory at: artifacts]
[2024-07-24 11:43:18,788: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 11:43:18,788: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:44:06,055: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:44:06,951: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-24 12:34:15,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:34:15,178: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:34:15,178: INFO: common: created directory at: artifacts]
[2024-07-24 12:45:56,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:45:56,578: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:45:56,579: INFO: common: created directory at: artifacts]
[2024-07-24 12:48:44,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:48:44,117: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:48:44,119: INFO: common: created directory at: artifacts]
[2024-07-24 12:55:24,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:55:24,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:55:24,015: INFO: common: created directory at: artifacts]
[2024-07-24 12:56:18,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:56:18,141: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:56:18,141: INFO: common: created directory at: artifacts]
[2024-07-24 12:56:26,024: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:56:26,027: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:56:26,028: INFO: common: created directory at: artifacts]
[2024-07-24 12:56:51,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:56:51,675: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:56:51,675: INFO: common: created directory at: artifacts]
[2024-07-24 12:57:09,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:57:09,999: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:57:10,003: INFO: common: created directory at: artifacts]
[2024-07-24 12:57:48,270: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:57:48,271: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:57:48,276: INFO: common: created directory at: artifacts]
[2024-07-24 13:01:33,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:01:33,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:01:33,196: INFO: common: created directory at: artifacts]
[2024-07-24 13:05:51,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:05:51,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:05:51,156: INFO: common: created directory at: artifacts]
[2024-07-24 13:06:02,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:06:02,604: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:06:02,606: INFO: common: created directory at: artifacts]
[2024-07-24 13:06:36,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:06:36,751: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:06:36,753: INFO: common: created directory at: artifacts]
[2024-07-24 13:07:08,577: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:07:08,580: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:07:08,582: INFO: common: created directory at: artifacts]
[2024-07-24 13:13:28,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:13:28,805: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:13:28,806: INFO: common: created directory at: artifacts]
[2024-07-24 13:13:41,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:13:41,853: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:13:41,854: INFO: common: created directory at: artifacts]
[2024-07-24 13:14:03,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:14:03,745: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:14:03,747: INFO: common: created directory at: artifacts]
[2024-07-24 13:14:53,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:14:53,544: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:14:53,545: INFO: common: created directory at: artifacts]
[2024-07-24 13:18:22,458: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:18:22,460: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:18:22,461: INFO: common: created directory at: artifacts]
[2024-07-24 13:20:41,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:20:41,046: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:20:41,048: INFO: common: created directory at: artifacts]
[2024-07-24 13:23:50,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:23:50,536: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:23:50,538: INFO: common: created directory at: artifacts]
[2024-07-24 13:24:37,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:24:37,995: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:24:37,996: INFO: common: created directory at: artifacts]
[2024-07-24 13:25:09,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:25:09,598: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:25:09,599: INFO: common: created directory at: artifacts]
[2024-07-24 13:25:51,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:25:51,951: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:25:51,953: INFO: common: created directory at: artifacts]
[2024-07-24 13:27:26,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:27:26,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:27:26,567: INFO: common: created directory at: artifacts]
[2024-07-24 13:29:20,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:29:20,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:29:20,282: INFO: common: created directory at: artifacts]
[2024-07-24 13:32:42,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:32:42,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:32:42,463: INFO: common: created directory at: artifacts]
[2024-07-24 13:41:16,978: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:41:16,981: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:41:16,982: INFO: common: created directory at: artifacts]
[2024-07-24 13:41:31,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:41:31,859: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:41:31,860: INFO: common: created directory at: artifacts]
[2024-07-24 13:41:31,862: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-24 13:42:10,741: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 14:01:29,770: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 14:01:29,773: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:01:29,774: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:01:29,774: INFO: common: created directory at: artifacts]
[2024-07-24 14:01:29,776: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 14:01:29,777: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 14:02:10,472: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 14:02:11,329: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-24 14:02:11,330: INFO: main: *******************]
[2024-07-24 14:02:11,330: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 14:02:11,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:02:11,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:02:11,335: INFO: common: created directory at: artifacts]
[2024-07-24 14:02:11,335: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-24 14:02:12,095: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 14:02:12,705: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-24 14:18:37,188: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:18:37,192: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:18:37,193: INFO: common: created directory at: artifacts]
[2024-07-24 14:20:00,424: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:20:00,427: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:20:00,429: INFO: common: created directory at: artifacts]
[2024-07-24 14:20:24,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:20:24,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:20:24,690: INFO: common: created directory at: artifacts]
[2024-07-24 14:20:24,691: INFO: common: created directory at: artifacts\training]
[2024-07-24 14:51:18,240: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 14:51:18,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:51:18,256: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:51:18,256: INFO: common: created directory at: artifacts]
[2024-07-24 14:51:18,256: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 14:51:18,256: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 14:51:53,327: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 14:51:54,112: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-24 14:51:54,113: INFO: main: *******************]
[2024-07-24 14:51:54,113: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 14:51:54,116: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:51:54,116: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:51:54,118: INFO: common: created directory at: artifacts]
[2024-07-24 14:51:54,119: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-24 14:51:54,714: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 14:51:55,195: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-24 14:51:55,196: INFO: main: *******************]
[2024-07-24 14:51:55,196: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-24 14:51:55,198: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:51:55,199: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:51:55,200: INFO: common: created directory at: artifacts]
[2024-07-24 14:51:55,202: INFO: common: created directory at: artifacts\training]
[2024-07-24 14:52:33,428: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 10:35:42,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 10:35:42,763: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 10:35:42,766: INFO: common: created directory at: artifacts]
[2024-07-25 10:35:59,696: INFO: common: json file saved at: scores.json]
[2024-07-25 10:36:05,209: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 10:36:06,312: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp9zvlv3om\model\data\model\assets]
[2024-07-25 10:50:29,379: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 10:50:29,400: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 10:50:29,403: INFO: common: created directory at: artifacts]
[2024-07-25 10:50:43,309: INFO: common: json file saved at: scores.json]
[2024-07-25 10:50:47,258: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 10:50:48,043: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpykd8ia4h\model\data\model\assets]
[2024-07-25 10:54:17,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 10:54:18,020: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 10:54:18,020: INFO: common: created directory at: artifacts]
[2024-07-25 10:54:35,086: INFO: common: json file saved at: scores.json]
[2024-07-25 10:54:39,816: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 10:54:40,745: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp0hnidr2_\model\data\model\assets]
[2024-07-25 11:16:05,115: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 11:16:05,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:16:05,131: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:16:05,131: INFO: common: created directory at: artifacts]
[2024-07-25 11:16:05,131: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 11:16:05,131: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 11:16:36,804: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 11:16:37,775: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 11:16:37,775: INFO: main: *******************]
[2024-07-25 11:16:37,775: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 11:16:37,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:16:37,788: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:16:37,788: INFO: common: created directory at: artifacts]
[2024-07-25 11:16:37,788: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 11:16:38,407: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 11:16:38,865: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 11:16:38,865: INFO: main: *******************]
[2024-07-25 11:16:38,865: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 11:16:38,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:16:38,865: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:16:38,865: INFO: common: created directory at: artifacts]
[2024-07-25 11:16:38,865: INFO: common: created directory at: artifacts\training]
[2024-07-25 11:17:13,367: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 11:17:13,367: INFO: main: *******************]
[2024-07-25 11:17:13,367: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 11:17:13,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:17:13,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:17:13,382: INFO: common: created directory at: artifacts]
[2024-07-25 11:17:23,789: INFO: common: json file saved at: scores.json]
[2024-07-25 11:17:23,789: INFO: common: json file saved at: scores.json]
[2024-07-25 11:17:23,789: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 11:30:31,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:30:31,960: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:30:31,965: INFO: common: created directory at: artifacts]
[2024-07-25 11:30:44,737: INFO: common: json file saved at: scores.json]
[2024-07-25 11:30:48,255: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 11:30:48,946: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp6uzbx3bm\model\data\model\assets]
[2024-07-25 11:33:47,287: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:33:47,349: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:33:47,349: INFO: common: created directory at: artifacts]
[2024-07-25 11:34:01,191: INFO: common: json file saved at: scores.json]
[2024-07-25 11:34:05,029: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 11:34:05,765: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpbnmazc1e\model\data\model\assets]
[2024-07-25 11:41:03,905: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 11:41:03,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:41:03,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:41:03,905: INFO: common: created directory at: artifacts]
[2024-07-25 11:41:03,905: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 11:41:03,905: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 11:41:39,615: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 11:41:40,642: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 11:41:40,642: INFO: main: *******************]
[2024-07-25 11:41:40,642: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 11:41:40,642: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:41:40,642: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:41:40,657: INFO: common: created directory at: artifacts]
[2024-07-25 11:41:40,657: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 11:41:41,477: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 11:41:41,935: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 11:41:41,951: INFO: main: *******************]
[2024-07-25 11:41:41,951: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 11:41:41,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:41:41,951: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:41:41,951: INFO: common: created directory at: artifacts]
[2024-07-25 11:41:41,951: INFO: common: created directory at: artifacts\training]
[2024-07-25 11:42:18,708: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 11:42:18,724: INFO: main: *******************]
[2024-07-25 11:42:18,724: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 11:42:18,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 11:42:18,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 11:42:18,732: INFO: common: created directory at: artifacts]
[2024-07-25 11:42:30,352: INFO: common: json file saved at: scores.json]
[2024-07-25 11:42:30,352: INFO: common: json file saved at: scores.json]
[2024-07-25 11:42:30,359: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:01:50,954: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 12:01:50,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:01:50,954: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:01:50,954: INFO: common: created directory at: artifacts]
[2024-07-25 12:01:50,954: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 12:01:50,954: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:02:31,137: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:02:31,892: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 12:02:31,893: INFO: main: *******************]
[2024-07-25 12:02:31,893: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 12:02:31,895: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:02:31,897: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:02:31,897: INFO: common: created directory at: artifacts]
[2024-07-25 12:02:31,898: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 12:02:32,509: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 12:02:32,836: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 12:02:32,836: INFO: main: *******************]
[2024-07-25 12:02:32,836: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 12:02:32,838: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:02:32,838: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:02:32,838: INFO: common: created directory at: artifacts]
[2024-07-25 12:02:32,838: INFO: common: created directory at: artifacts\training]
[2024-07-25 12:03:06,338: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 12:03:06,338: INFO: main: *******************]
[2024-07-25 12:03:06,338: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 12:03:06,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:03:06,338: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:03:06,338: INFO: common: created directory at: artifacts]
[2024-07-25 12:03:17,004: INFO: common: json file saved at: scores.json]
[2024-07-25 12:03:17,004: INFO: common: json file saved at: scores.json]
[2024-07-25 12:03:17,004: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:14:28,438: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 12:14:28,438: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:14:28,453: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:14:28,453: INFO: common: created directory at: artifacts]
[2024-07-25 12:14:28,453: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 12:14:28,453: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:15:13,254: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:15:13,993: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 12:15:13,993: INFO: main: *******************]
[2024-07-25 12:15:13,993: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 12:15:13,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:15:13,998: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:15:13,998: INFO: common: created directory at: artifacts]
[2024-07-25 12:15:13,998: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 12:15:14,595: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 12:15:14,933: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 12:15:14,933: INFO: main: *******************]
[2024-07-25 12:15:14,933: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 12:15:14,936: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:15:14,939: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:15:14,939: INFO: common: created directory at: artifacts]
[2024-07-25 12:15:14,939: INFO: common: created directory at: artifacts\training]
[2024-07-25 12:16:19,538: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 12:16:19,538: INFO: main: *******************]
[2024-07-25 12:16:19,538: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 12:16:19,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:16:19,554: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:16:19,554: INFO: common: created directory at: artifacts]
[2024-07-25 12:16:29,409: INFO: common: json file saved at: scores.json]
[2024-07-25 12:16:29,409: INFO: common: json file saved at: scores.json]
[2024-07-25 12:16:29,409: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:19:18,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:19:18,861: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:19:18,861: INFO: common: created directory at: artifacts]
[2024-07-25 12:19:31,722: INFO: common: json file saved at: scores.json]
[2024-07-25 12:19:35,650: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 12:19:36,389: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpwcem6c0j\model\data\model\assets]
[2024-07-25 12:22:03,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:22:03,184: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:22:03,186: INFO: common: created directory at: artifacts]
[2024-07-25 12:22:15,557: INFO: common: json file saved at: scores.json]
[2024-07-25 12:22:19,511: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 12:22:20,301: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpid9xg9_c\model\data\model\assets]
[2024-07-25 12:24:31,446: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 12:24:31,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:24:31,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:24:31,462: INFO: common: created directory at: artifacts]
[2024-07-25 12:24:31,462: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 12:24:31,462: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:25:12,623: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:25:13,327: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 12:25:13,327: INFO: main: *******************]
[2024-07-25 12:25:13,327: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 12:25:13,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:25:13,343: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:25:13,343: INFO: common: created directory at: artifacts]
[2024-07-25 12:25:13,343: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 12:25:13,844: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 12:25:14,173: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 12:25:14,173: INFO: main: *******************]
[2024-07-25 12:25:14,173: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 12:25:14,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:25:14,173: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:25:14,173: INFO: common: created directory at: artifacts]
[2024-07-25 12:25:14,173: INFO: common: created directory at: artifacts\training]
[2024-07-25 12:25:46,277: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 12:25:46,277: INFO: main: *******************]
[2024-07-25 12:25:46,277: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 12:25:46,292: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:25:46,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:25:46,292: INFO: common: created directory at: artifacts]
[2024-07-25 12:25:55,704: INFO: common: json file saved at: scores.json]
[2024-07-25 12:25:55,704: INFO: common: json file saved at: scores.json]
[2024-07-25 12:25:55,704: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:27:33,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:27:33,686: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:27:33,688: INFO: common: created directory at: artifacts]
[2024-07-25 12:27:47,974: INFO: common: json file saved at: scores.json]
[2024-07-25 12:27:50,790: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 12:27:51,519: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpv_qwz_eg\model\data\model\assets]
[2024-07-25 12:37:36,295: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 12:37:36,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:37:36,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:37:36,311: INFO: common: created directory at: artifacts]
[2024-07-25 12:37:36,311: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 12:37:36,311: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:38:17,188: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:38:17,963: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 12:38:17,963: INFO: main: *******************]
[2024-07-25 12:38:17,963: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 12:38:17,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:38:17,963: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:38:17,963: INFO: common: created directory at: artifacts]
[2024-07-25 12:38:17,963: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 12:38:18,912: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 12:38:19,889: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 12:38:19,889: INFO: main: *******************]
[2024-07-25 12:38:19,889: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 12:38:19,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:38:19,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:38:19,905: INFO: common: created directory at: artifacts]
[2024-07-25 12:38:19,905: INFO: common: created directory at: artifacts\training]
[2024-07-25 12:39:20,208: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 12:39:20,208: INFO: main: *******************]
[2024-07-25 12:39:20,208: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 12:39:20,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:39:20,224: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:39:20,224: INFO: common: created directory at: artifacts]
[2024-07-25 12:39:30,894: INFO: common: json file saved at: scores.json]
[2024-07-25 12:39:30,894: INFO: common: json file saved at: scores.json]
[2024-07-25 12:39:30,894: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:40:12,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:40:12,011: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:40:12,017: INFO: common: created directory at: artifacts]
[2024-07-25 12:40:24,587: INFO: common: json file saved at: scores.json]
[2024-07-25 12:40:28,121: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 12:40:28,858: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpokbin1se\model\data\model\assets]
[2024-07-25 12:42:00,710: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 12:42:00,726: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:42:00,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:42:00,726: INFO: common: created directory at: artifacts]
[2024-07-25 12:42:00,726: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 12:42:00,726: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:42:42,575: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:42:43,219: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 12:42:43,219: INFO: main: *******************]
[2024-07-25 12:42:43,219: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 12:42:43,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:42:43,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:42:43,219: INFO: common: created directory at: artifacts]
[2024-07-25 12:42:43,219: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 12:42:43,689: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 12:42:43,957: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 12:42:43,957: INFO: main: *******************]
[2024-07-25 12:42:43,957: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 12:42:43,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:42:43,957: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:42:43,957: INFO: common: created directory at: artifacts]
[2024-07-25 12:42:43,973: INFO: common: created directory at: artifacts\training]
[2024-07-25 12:43:41,580: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 12:43:41,580: INFO: main: *******************]
[2024-07-25 12:43:41,580: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 12:43:41,580: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:43:41,596: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:43:41,596: INFO: common: created directory at: artifacts]
[2024-07-25 12:43:52,097: INFO: common: json file saved at: scores.json]
[2024-07-25 12:43:52,097: INFO: common: json file saved at: scores.json]
[2024-07-25 12:43:52,097: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:44:22,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:44:22,213: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:44:22,214: INFO: common: created directory at: artifacts]
[2024-07-25 12:44:34,117: INFO: common: json file saved at: scores.json]
[2024-07-25 12:44:37,390: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 12:44:38,090: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpj0p01cg_\model\data\model\assets]
[2024-07-25 12:46:35,011: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 12:46:35,016: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:46:35,025: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:46:35,025: INFO: common: created directory at: artifacts]
[2024-07-25 12:46:35,025: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 12:46:35,025: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:47:20,211: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 12:47:20,888: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 12:47:20,888: INFO: main: *******************]
[2024-07-25 12:47:20,888: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 12:47:20,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:47:20,904: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:47:20,904: INFO: common: created directory at: artifacts]
[2024-07-25 12:47:20,904: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 12:47:21,424: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 12:47:21,771: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 12:47:21,771: INFO: main: *******************]
[2024-07-25 12:47:21,771: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 12:47:21,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:47:21,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:47:21,771: INFO: common: created directory at: artifacts]
[2024-07-25 12:47:21,771: INFO: common: created directory at: artifacts\training]
[2024-07-25 12:47:53,241: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 12:47:53,241: INFO: main: *******************]
[2024-07-25 12:47:53,241: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 12:47:53,241: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:47:53,241: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:47:53,241: INFO: common: created directory at: artifacts]
[2024-07-25 12:48:03,124: INFO: common: json file saved at: scores.json]
[2024-07-25 12:48:03,124: INFO: common: json file saved at: scores.json]
[2024-07-25 12:48:03,124: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 12:48:39,770: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 12:48:39,770: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 12:48:39,770: INFO: common: created directory at: artifacts]
[2024-07-25 12:48:50,787: INFO: common: json file saved at: scores.json]
[2024-07-25 12:48:53,855: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 12:48:54,489: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp2vizcvf4\model\data\model\assets]
[2024-07-25 14:56:09,187: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 14:56:09,190: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 14:56:09,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 14:56:09,195: INFO: common: created directory at: artifacts]
[2024-07-25 14:56:09,195: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 14:56:09,196: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 14:56:48,605: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 14:56:49,517: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 14:57:05,865: INFO: stage_02_prepare_base_model: *******************]
[2024-07-25 14:57:05,865: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 14:57:05,869: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 14:57:05,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 14:57:05,872: INFO: common: created directory at: artifacts]
[2024-07-25 14:57:05,872: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 14:57:06,509: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 14:57:06,879: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 14:57:13,799: INFO: stage_03_model_training: *******************]
[2024-07-25 14:57:13,799: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-07-25 14:57:13,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 14:57:13,804: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 14:57:13,804: INFO: common: created directory at: artifacts]
[2024-07-25 14:57:13,805: INFO: common: created directory at: artifacts\training]
[2024-07-25 14:57:53,227: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 14:58:02,331: INFO: stage_04_model_evaluation: *******************]
[2024-07-25 14:58:02,331: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 14:58:02,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 14:58:02,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 14:58:02,437: INFO: common: created directory at: artifacts]
[2024-07-25 14:58:15,341: INFO: common: json file saved at: scores.json]
[2024-07-25 14:58:15,343: INFO: common: json file saved at: scores.json]
[2024-07-25 14:58:15,343: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 15:26:50,654: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 15:26:50,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:26:50,654: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:26:50,654: INFO: common: created directory at: artifacts]
[2024-07-25 15:26:50,654: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 15:26:50,654: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:27:30,243: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:27:31,374: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 15:27:31,374: INFO: main: *******************]
[2024-07-25 15:27:31,374: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 15:27:31,378: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:27:31,380: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:27:31,380: INFO: common: created directory at: artifacts]
[2024-07-25 15:27:31,381: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 15:27:32,559: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 15:27:33,250: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 15:27:33,250: INFO: main: *******************]
[2024-07-25 15:27:33,250: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 15:27:33,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:27:33,260: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:27:33,262: INFO: common: created directory at: artifacts]
[2024-07-25 15:27:33,263: INFO: common: created directory at: artifacts\training]
[2024-07-25 15:28:15,331: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 15:28:15,331: INFO: main: *******************]
[2024-07-25 15:28:15,331: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 15:28:15,336: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:28:15,340: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:28:15,343: INFO: common: created directory at: artifacts]
[2024-07-25 15:28:27,588: INFO: common: json file saved at: scores.json]
[2024-07-25 15:28:27,588: INFO: common: json file saved at: scores.json]
[2024-07-25 15:28:27,588: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 15:35:15,555: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 15:35:15,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:35:15,555: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:35:15,555: INFO: common: created directory at: artifacts]
[2024-07-25 15:35:15,555: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 15:35:15,555: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:36:02,019: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:36:02,665: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 15:36:02,665: INFO: main: *******************]
[2024-07-25 15:36:02,665: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 15:36:02,665: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:36:02,665: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:36:02,665: INFO: common: created directory at: artifacts]
[2024-07-25 15:36:02,665: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 15:36:03,247: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 15:36:03,719: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 15:36:03,719: INFO: main: *******************]
[2024-07-25 15:36:03,719: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 15:36:03,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:36:03,719: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:36:03,719: INFO: common: created directory at: artifacts]
[2024-07-25 15:36:03,719: INFO: common: created directory at: artifacts\training]
[2024-07-25 15:36:49,428: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 15:36:49,431: INFO: main: *******************]
[2024-07-25 15:36:49,432: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 15:36:49,436: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:36:49,440: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:36:49,442: INFO: common: created directory at: artifacts]
[2024-07-25 15:37:03,419: INFO: common: json file saved at: scores.json]
[2024-07-25 15:37:03,421: INFO: common: json file saved at: scores.json]
[2024-07-25 15:37:05,597: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 15:37:06,256: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpzbz0zz7p\model\data\model\assets]
[2024-07-25 15:37:23,834: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 15:45:36,439: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 15:45:36,439: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:45:36,455: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:45:36,455: INFO: common: created directory at: artifacts]
[2024-07-25 15:45:36,455: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 15:45:36,455: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:45:55,195: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:45:55,934: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 15:45:55,934: INFO: main: *******************]
[2024-07-25 15:45:55,935: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 15:45:55,936: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:45:55,937: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:45:55,937: INFO: common: created directory at: artifacts]
[2024-07-25 15:45:55,939: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 15:45:56,534: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 15:45:57,117: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 15:45:57,117: INFO: main: *******************]
[2024-07-25 15:45:57,117: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 15:45:57,123: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:45:57,123: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:45:57,123: INFO: common: created directory at: artifacts]
[2024-07-25 15:45:57,123: INFO: common: created directory at: artifacts\training]
[2024-07-25 15:46:37,569: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-25 15:46:37,569: INFO: main: *******************]
[2024-07-25 15:46:37,569: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-25 15:46:37,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:46:37,585: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:46:37,588: INFO: common: created directory at: artifacts]
[2024-07-25 15:46:49,097: INFO: common: json file saved at: scores.json]
[2024-07-25 15:46:49,099: INFO: common: json file saved at: scores.json]
[2024-07-25 15:46:50,531: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-25 15:46:51,154: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpc0s_j_sc\model\data\model\assets]
[2024-07-25 15:47:04,520: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-25 15:47:46,454: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2024-07-25 15:47:46,454: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 15:51:01,711: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2024-07-25 15:51:01,711: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 15:51:38,874: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:51:38] "GET / HTTP/1.1" 200 -]
[2024-07-25 15:52:13,001: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 15:52:13,049: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:52:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 15:54:21,838: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2024-07-25 15:54:21,838: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 15:54:21,950: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:54:21] "GET / HTTP/1.1" 200 -]
[2024-07-25 15:54:38,440: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:54:38] "GET / HTTP/1.1" 200 -]
[2024-07-25 15:54:47,952: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 15:54:47,965: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:54:47] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 15:55:00,826: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 15:55:00,834: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:55:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 15:55:13,073: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:55:13] "GET / HTTP/1.1" 200 -]
[2024-07-25 15:55:26,229: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:55:26] "GET / HTTP/1.1" 200 -]
[2024-07-25 15:57:22,052: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-25 15:57:22,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:57:22,068: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:57:22,068: INFO: common: created directory at: artifacts]
[2024-07-25 15:57:22,068: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-25 15:57:22,068: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:58:09,505: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-25 15:58:10,222: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-25 15:58:10,222: INFO: main: *******************]
[2024-07-25 15:58:10,222: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-25 15:58:10,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:58:10,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:58:10,222: INFO: common: created directory at: artifacts]
[2024-07-25 15:58:10,222: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-25 15:58:10,821: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-25 15:58:11,295: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-25 15:58:11,295: INFO: main: *******************]
[2024-07-25 15:58:11,311: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-25 15:58:11,311: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-25 15:58:11,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-25 15:58:11,311: INFO: common: created directory at: artifacts]
[2024-07-25 15:58:11,311: INFO: common: created directory at: artifacts\training]
[2024-07-25 15:58:36,471: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2024-07-25 15:58:36,471: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 15:58:43,861: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:58:43] "GET / HTTP/1.1" 200 -]
[2024-07-25 15:58:49,757: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 15:58:49,770: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:58:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 15:59:56,854: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 15:59:56] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:00:09,457: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:00:09,464: INFO: _internal: 192.168.1.3 - - [25/Jul/2024 16:00:09] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 16:05:29,275: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2024-07-25 16:05:29,276: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 16:08:59,152: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.1.3:8081]
[2024-07-25 16:08:59,152: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 16:09:05,156: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:09:05] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:09:15,970: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:09:15,986: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:09:15] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 16:09:54,607: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:09:54] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:09:54,894: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:09:54] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:09:55,036: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:09:55] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:13:57,670: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.1.3:8081]
[2024-07-25 16:13:57,670: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 16:14:01,098: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:14:01] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:14:07,227: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:14:07,233: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:14:07] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 16:16:50,872: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.1.3:8081]
[2024-07-25 16:16:50,872: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 16:16:52,286: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:16:52] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:17:01,747: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:17:01,761: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:17:01] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 16:34:36,368: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.1.3:8081]
[2024-07-25 16:34:36,368: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 16:34:41,723: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:34:41] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:34:52,237: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:34:52,250: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:34:52] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 16:38:13,176: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.1.3:8081]
[2024-07-25 16:38:13,176: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 16:38:16,909: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:38:16] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:38:25,049: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:38:25,056: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:38:25] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 16:55:45,747: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:55:45] "GET / HTTP/1.1" 200 -]
[2024-07-25 16:55:50,955: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-07-25 16:55:51,066: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 16:55:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-25 17:10:42,050: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.1.3:8081]
[2024-07-25 17:10:42,050: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-25 17:10:44,346: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:10:44] "GET / HTTP/1.1" 200 -]
[2024-07-25 17:10:51,050: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:10:51] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:11:54,860: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:11:54] "GET / HTTP/1.1" 200 -]
[2024-07-25 17:12:10,987: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:12:10] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:12:43,209: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:12:43] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:13:19,084: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:13:19] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:13:40,202: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001EDADF614E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-07-25 17:13:40,209: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:13:40] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:14:01,195: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001EDADF60360> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-07-25 17:14:01,202: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:14:01] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:14:03,570: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:14:03] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:14:13,494: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:14:13] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:14:25,952: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:14:25] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:14:32,424: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:14:32] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:14:44,202: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:14:44] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:17:28,730: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:17:28] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:17:39,451: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:17:39] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:17:47,333: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:17:47] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:18:00,861: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:18:00] "POST /predict HTTP/1.1" 200 -]
[2024-07-25 17:18:10,924: INFO: _internal: 127.0.0.1 - - [25/Jul/2024 17:18:10] "POST /predict HTTP/1.1" 200 -]
